#!/usr/bin/env bash
# Retired on 2026-09-24: the old roots are covered by the verified central cleanup.
printf '%s\n' 'This historical cleanup script is retired. See LegacyResearchAssets and docs/MEX_RECOVERY.md.' >&2
exit 1

#
# cleanup_originals.sh — remove, from the old MATLAB workspaces, the intermediate
# results, figures and raw dataset files left out of the consolidated TSSM
# project, plus two local folders that TSSM fully supersedes.
#
# (A) Data sweep: regenerable results (.mat/.fig/.tif/.png/.eps/.asv/.log) and raw
#     dataset files re-obtainable from public sources.  ALL CODE IS LEFT IN PLACE,
#     including code of other, not yet consolidated work (e.g. NTU run.m).
# (B) Local folders superseded by TSSM, deleted whole after the guard re-verifies them.
#
# Untouched: IP, UCF-Kinect, UT-Kinect, MSR-DailyActivity folders, and every code
# file on the shares.  SMB deletions do NOT go to the Trash.
#
# Usage:  ./cleanup_originals.sh           # dry run
#         ./cleanup_originals.sh --apply   # delete
# Do not edit this file while it is running.
#
set -uo pipefail

SHARE1="/Volumes/OneTouch/MatlabProjects/work"
SHARE2="/Volumes/9592df65-5b85-4531-8d5e-3ec20c74afc8/work"
LOCAL="/Users/perryshao/Documents/Projects/Work"
TSSM="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

APPLY=0
[ "${1:-}" = "--apply" ] && APPLY=1

for m in "$SHARE1" "$SHARE2"; do
    [ -d "$m" ] || { echo "ERROR: $m not mounted. Reconnect and re-run. Nothing touched." >&2; exit 1; }
done
if [ ! -f "$TSSM/ssm/Temporal_SSM.m" ] || [ ! -f "$TSSM/loghog/src/LogHog.cpp" ]; then
    echo "ERROR: $TSSM looks incomplete — refusing to delete anything." >&2; exit 1
fi

# .txt included (skeleton datasets are text) but readme/licence excluded by name.
# .dat and .pdf never touched (ScSPM's README is README.dat).
DATA=( \( -name '*.mat' -o -name '*.fig' -o -name '*.tif' -o -name '*.png'
          -o -name '*.jpg' -o -name '*.eps' -o -name '*.asv' -o -name '*.log'
          -o -name '*.csv' -o -name '*.tagstream' -o -name '*.txt' \)
       ! -iname 'readme*' ! -iname 'license*' ! -iname 'copying*' )

total=0
sweep () {          # $1 = directory, $2 = label
    local dir="$1" label="$2"
    [ -d "$dir" ] || { echo "  skip (missing): $dir"; return; }
    local n bytes
    n=$(find "$dir" -type f "${DATA[@]}" 2>/dev/null | wc -l | tr -d ' ')
    bytes=$(find "$dir" -type f "${DATA[@]}" -exec stat -f%z {} + 2>/dev/null \
            | awk '{s+=$1} END {printf "%.0f", s}')
    bytes=${bytes:-0}; total=$((total + bytes))
    printf "  %-7s %-34s %7s files  %9.1f MB\n" "$label" "$(basename "$dir")" "$n" "$(echo "$bytes/1048576" | bc -l)"
    if [ "$APPLY" = "1" ] && [ "$n" -gt 0 ]; then
        find "$dir" -type f "${DATA[@]}" -delete 2>/dev/null
        find "$dir" -type d -empty -delete 2>/dev/null
    fi
}

echo "=== (A) data sweep — code is left in place ==="
sweep "$SHARE1/MSRActionEvaluatingCode"          share1
sweep "$SHARE1/ScSPM"                            share1
sweep "$SHARE1/fast_sc"                          share1
sweep "$SHARE1/sc_demo"                          share1
sweep "$SHARE2/NTU3DActionEvaluatingCode"        share2
sweep "$SHARE2/MicrosoftGestureEvaluatingCode"   share2
sweep "$SHARE2/ScSPM"                            share2
sweep "$LOCAL/MSRActionEvaluatingCode"           local
sweep "$LOCAL/MicrosoftGestureEvaluatingCode"    local
sweep "$LOCAL/NTU3DActionEvaluatingCode"         local

# find's errors go to /dev/null, so re-check the shares are still there.
SHARE_LOST=0
if [ ! -d "$SHARE1/MSRActionEvaluatingCode" ] || [ ! -d "$SHARE2/NTU3DActionEvaluatingCode" ]; then
    SHARE_LOST=1
    echo "!! WARNING: a share dropped mid-run; figures unreliable. Reconnect and re-run (resumes safely)." >&2
fi

echo
echo "=== (B) local folders superseded by TSSM ==="
drop () {           # $1 = directory, $2 = ok | reason for refusing
    local dir="$1" verdict="$2"
    [ -d "$dir" ] || { echo "  skip (missing): $(basename "$dir")"; return; }
    local sz bytes; sz=$(du -sh "$dir" 2>/dev/null | cut -f1)
    if [ "$verdict" != "ok" ]; then
        printf "  %-18s %8s  REFUSED — %s\n" "$(basename "$dir")" "$sz" "$verdict"; return
    fi
    printf "  %-18s %8s  superseded\n" "$(basename "$dir")" "$sz"
    bytes=$(find "$dir" -type f -exec stat -f%z {} + 2>/dev/null | awk '{s+=$1} END {printf "%.0f", s}')
    total=$((total + ${bytes:-0}))
    [ "$APPLY" = "1" ] && rm -rf "$dir"
}

# CostFuncRegMex: an empty VS project — must contain no source file at all.
cfr="$LOCAL/CostFuncRegMex"
if [ -d "$cfr" ]; then
    src=$(find "$cfr" -type f \( -name '*.c' -o -name '*.cpp' -o -name '*.h' -o -name '*.hpp' -o -name '*.m' \) | wc -l | tr -d ' ')
    if [ "$src" = "0" ]; then drop "$cfr" ok; else drop "$cfr" "$src source file(s) found"; fi
fi

# Log_Hog: the zip's three LogHog sources must be byte-identical to TSSM's copies.
# The rest is VS build output or the stock mexopencv library, unused by LogHog.cpp.
lh="$LOCAL/Log_Hog"
if [ -d "$lh" ]; then
    verdict=ok
    for f in LogHog.cpp log_hogcalculator.cpp log_hogcalculator.h; do
        a=$(unzip -p "$lh/Log_Hog.zip" "Log_Hog/Log_Hog/$f" 2>/dev/null | md5 -q)
        b=$(md5 -q "$TSSM/loghog/src/$f" 2>/dev/null)
        if [ -z "$b" ] || [ "$a" != "$b" ]; then verdict="$f differs from TSSM/loghog/src"; break; fi
    done
    drop "$lh" "$verdict"
fi

echo
if [ "$SHARE_LOST" = "1" ]; then
    printf "TOTAL (UNRELIABLE): %.2f GB\n" "$(echo "$total/1073741824" | bc -l)"; exit 3
fi
printf "TOTAL: %.2f GB %s\n" "$(echo "$total/1073741824" | bc -l)" \
       "$( [ "$APPLY" = "1" ] && echo 'DELETED' || echo 'would be deleted (dry run)')"
[ "$APPLY" = "1" ] || echo "This was a DRY RUN. Re-run with --apply to actually delete."